"""Per-cell regression on GOLD-FILTERED cells: Δ_c = α + β·(lex_L − lex_R)_c.

The regression is fit on (article, frame) cells where both the L-coded and
R-coded query of the cell surface a same-story counterpart (any of the L/C/R
triplet from the original AllSides roundup) within top-K.

Sign convention: Δ_c = lean(L) − lean(R) and the regressor lex_L − lex_R are
the negatives of the paper's R − L convention, so the paper's Δ and α (and
their CIs) are these values negated; β and the p-values are unchanged.

Motivation: the unfiltered regression confounds the lex-residual α with cells
where the retriever fails to find anything story-relevant for one or both
queries — in those cells, Δ_c is dominated by mechanical corpus-composition
noise rather than the within-cell paired contrast we want to decompose.

Outputs:
  allsides_synth/results/lex_regression_per_encoder_gold_filtered.csv
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd
import statsmodels.api as sm

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from src.stats import stable_seed  # noqa: E402

OUT_DIR = ROOT / "allsides_synth" / "results"
LEX = OUT_DIR / "cell_lex_asymmetry.csv"
DENSE_RUN = ROOT / "allsides_synth" / "results"
BM25_RUN = DENSE_RUN / "bm25"
ENCODERS = (
    "bge-large-en-v1.5",
    "qwen3-embedding-8b",
    "llama-embed-nemotron-8b",
    "octen-embedding-8b",
    "text-embedding-3-large",
    "bm25",
)
K = 10
SEED = 1234
N_BOOT = 5000


def _min_story_rank(run_dir: Path) -> pd.DataFrame:
    """Committed gold-filter cache: per (query_id, encoder), the smallest rank
    where any same-story (same AllSides roundup) doc is retrieved. The dense
    cache is regenerated by allsides_synth/scripts/retrieve.py; the bm25/
    cache has no regeneration script."""
    cache = run_dir / "_min_story_rank.parquet"
    if not cache.exists():
        raise FileNotFoundError(
            f"{cache} not found — it is a committed gold-filter cache "
            "(dense run: regenerated by allsides_synth/scripts/retrieve.py; "
            "bm25/: committed only, no regeneration script). "
            "Restore it from git or, for the dense run, re-run retrieval."
        )
    return pd.read_parquet(cache)


def _load_paired_with_gold_mask(run_dir: Path) -> pd.DataFrame:
    """Return one row per (encoder, article_id, frame) with delta_lr and
    a `passes_both` boolean (both L and R retrieved any same-story doc in top-K).
    """
    bm = pd.read_csv(run_dir / "bias_metrics.csv",
                     usecols=["query_id", "article_id", "frame", "stance",
                              "encoder", "k", "lean_score"])
    bm = bm[bm["k"] == K]
    sr = _min_story_rank(run_dir)
    bm = bm.merge(sr, on=["query_id", "encoder"], how="left")
    bm["passes"] = (bm["min_story_rank"] <= K).fillna(False)

    lr = bm[bm["stance"].isin(["left", "right"])].copy()
    wide = lr.pivot_table(index=["encoder", "article_id", "frame"],
                          columns="stance",
                          values=["lean_score", "passes"],
                          aggfunc="first")
    wide.columns = [f"{a}_{b}" for a, b in wide.columns]
    wide = wide.reset_index()
    wide["delta_lr"] = wide["lean_score_left"] - wide["lean_score_right"]
    wide["passes_both"] = (wide["passes_left"] == True) & (wide["passes_right"] == True)
    return wide.dropna(subset=["delta_lr"])


def main() -> None:
    lex = pd.read_csv(LEX)[["article_id", "frame", "lex_diff_lr"]]
    paired_dense = _load_paired_with_gold_mask(DENSE_RUN)
    paired_bm = _load_paired_with_gold_mask(BM25_RUN)
    paired = pd.concat([paired_dense, paired_bm], ignore_index=True)
    paired = paired.merge(lex, on=["article_id", "frame"], how="inner")
    print(f"Joined {len(paired)} (encoder × cell) rows with lex_diff_lr")

    out = []
    for enc in ENCODERS:
        sub_all = paired[paired["encoder"] == enc].copy()
        sub = sub_all[sub_all["passes_both"]].copy()
        n = len(sub)
        if n == 0:
            print(f"  {enc}: no gold-filtered cells; skipping")
            continue
        y = sub["delta_lr"].to_numpy()
        x = sub["lex_diff_lr"].to_numpy()
        X = sm.add_constant(x)
        model = sm.OLS(y, X).fit(cov_type="cluster",
                                 cov_kwds={"groups": sub["article_id"].to_numpy()})
        alpha = float(model.params[0])
        beta = float(model.params[1])
        raw_delta_gold = float(y.mean())
        raw_delta_all = float(sub_all["delta_lr"].mean())
        rng = np.random.default_rng(stable_seed(enc, base=SEED))
        clusters = sub["article_id"].to_numpy()
        uniq = np.unique(clusters)
        cluster_to_idx = {c: np.where(clusters == c)[0] for c in uniq}
        boots = np.empty(N_BOOT, dtype=float)
        for b in range(N_BOOT):
            sampled = rng.choice(uniq, size=len(uniq), replace=True)
            idx = np.concatenate([cluster_to_idx[c] for c in sampled])
            yb, xb = y[idx], x[idx]
            Xb = sm.add_constant(xb)
            try:
                pb = np.linalg.lstsq(Xb, yb, rcond=None)[0]
                boots[b] = pb[0]
            except np.linalg.LinAlgError:
                boots[b] = np.nan
        alpha_lo, alpha_hi = float(np.nanpercentile(boots, 2.5)), float(np.nanpercentile(boots, 97.5))
        lex_mean = float(x.mean())
        lex_contrib = beta * lex_mean
        out.append({
            "encoder": enc,
            "n_cells_gold": n,
            "n_cells_all": int(len(sub_all)),
            "raw_delta_gold": raw_delta_gold,
            "raw_delta_all": raw_delta_all,
            "alpha": alpha,
            "alpha_ci_low": alpha_lo,
            "alpha_ci_high": alpha_hi,
            "beta": beta,
            "beta_se": float(model.bse[1]),
            "beta_p": float(model.pvalues[1]),
            "intercept_p": float(model.pvalues[0]),
            "r2": float(model.rsquared),
            "lex_mean_in_gold": lex_mean,
            "lex_contrib_at_mean": lex_contrib,
            "residual_pct_of_raw": 100.0 * alpha / raw_delta_gold if raw_delta_gold else float("nan"),
        })
    rep = pd.DataFrame(out)
    out_path = OUT_DIR / "lex_regression_per_encoder_gold_filtered.csv"
    rep.to_csv(out_path, index=False)
    print()
    print(rep.round(5).to_string(index=False))
    print(f"\nwrote {out_path}")


if __name__ == "__main__":
    main()
