"""Per-encoder paired test on gold-filtered cells at k=10.

A cell survives the gold filter iff *both* its L-coded and R-coded queries
have any same-story counterpart (any stance from the L/C/R triplet) in the
top-10 retrieved set. Pair-filtering is required so Δ_c = lean(L) − lean(R)
remains a within-cell paired contrast. The paper reports R − L, so its mean Δ
and CI are these values negated; the p-values are unchanged.

For each encoder we report:
  - n_cells_total      : 3,723 (article, frame) cells before filtering
  - n_cells_filtered   : cells with both L and R passing the gold filter
  - mean Δ on filtered cells, cluster-bootstrap 95% CI (cluster = article_id)
  - sign-flip permutation p (B=50,000) on the filtered sample

Writes:
  figs/results/gold_filtered_paired_test_k10.csv
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd
from scipy import stats as scipy_stats

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(REPO / "figs" / "scripts"))

from src.stats import cluster_bootstrap_mean, signflip_permutation_p  # noqa: E402
from _style import ENCODER_DISPLAY, ENCODER_ORDER  # noqa: E402

DENSE_RUN = REPO / "allsides_synth" / "results"
BM25_RUN = DENSE_RUN / "bm25"
DISPLAY_NAMES = dict(ENCODER_DISPLAY, **{"bm25": "BM25"})

K = 10
N_PERM = 50000


def _min_story_rank(run_dir: Path) -> pd.DataFrame:
    """Committed gold-filter cache: per (query_id, encoder), the smallest rank
    where any same-story (same AllSides roundup) doc is retrieved. The dense
    cache is regenerated by allsides_synth/scripts/retrieve.py; the bm25/
    cache has no regeneration script."""
    cache = run_dir / "_min_story_rank.parquet"
    if not cache.exists():
        raise FileNotFoundError(
            f"{cache} not found — it is a committed gold-filter cache "
            "(dense run: regenerated by allsides_synth/scripts/retrieve.py; "
            "bm25/: committed only, no regeneration script). "
            "Restore it from git or, for the dense run, re-run retrieval."
        )
    return pd.read_parquet(cache)


def _load_filtered_pairs(run_dir: Path) -> pd.DataFrame:
    """Return DataFrame with one row per (article, frame, encoder) cell where
    both L and R queries have any same-story doc in top-K. Columns:
    encoder, article_id, frame, lean_L, lean_R, delta.
    """
    bm = pd.read_csv(run_dir / "bias_metrics.csv")
    bm = bm[bm["k"] == K]
    sr = _min_story_rank(run_dir)
    bm = bm.merge(sr, on=["query_id", "encoder"], how="left")
    bm["passes"] = (bm["min_story_rank"] <= K).fillna(False)

    # Filter to L and R only, pivot to wide.
    lr = bm[bm["stance"].isin(["left", "right"])].copy()
    keep = ["encoder", "article_id", "frame", "stance", "lean_score", "passes"]
    lr = lr[keep]
    wide = lr.pivot_table(index=["encoder", "article_id", "frame"],
                          columns="stance",
                          values=["lean_score", "passes"],
                          aggfunc="first")
    wide.columns = [f"{a}_{b}" for a, b in wide.columns]
    wide = wide.reset_index()
    # Keep cells where both L and R passed
    paired = wide[(wide["passes_left"] == True)
                  & (wide["passes_right"] == True)].copy()
    paired["delta"] = paired["lean_score_left"] - paired["lean_score_right"]
    return paired


def main() -> None:
    print(f"[gold-test] k = {K}, sign-flip permutation B = {N_PERM:,}")

    rows = []
    for enc in list(ENCODER_ORDER) + ["bm25"]:
        run_dir = BM25_RUN if enc == "bm25" else DENSE_RUN
        paired_all = _load_filtered_pairs(run_dir)
        paired = paired_all[paired_all["encoder"] == enc]
        # Total cells before filtering = all (article, frame) for this encoder
        all_cells = pd.read_csv(run_dir / "bias_metrics.csv")
        all_cells = all_cells[(all_cells["k"] == K) & (all_cells["encoder"] == enc)]
        # one row per (article, frame, stance); we want # distinct cells
        n_total = all_cells.drop_duplicates(
            subset=["article_id", "frame"]
        ).shape[0]

        n_filt = paired.shape[0]
        delta_vals = paired["delta"].to_numpy()
        clusters = paired["article_id"].to_numpy()
        if len(delta_vals) == 0:
            mean = float("nan"); lo = float("nan"); hi = float("nan")
            p_perm = float("nan"); p_wilc = float("nan")
        else:
            mean, lo, hi = cluster_bootstrap_mean(delta_vals, clusters,
                                                   n_boot=5000, seed=42)
            perm = signflip_permutation_p(delta_vals, n_perm=N_PERM, seed=42)
            p_perm = float(perm["p_two_sided"])
            # Paired Wilcoxon signed-rank on Δ_c (two-sided, zero_method=wilcox)
            try:
                wilc = scipy_stats.wilcoxon(delta_vals, zero_method="wilcox",
                                            alternative="two-sided")
                p_wilc = float(wilc.pvalue)
            except ValueError:
                p_wilc = float("nan")
        n_articles = paired["article_id"].nunique() if n_filt > 0 else 0
        rows.append({
            "encoder": enc,
            "display": DISPLAY_NAMES[enc],
            "n_cells_total": int(n_total),
            "n_cells_filtered": int(n_filt),
            "n_articles_filtered": int(n_articles),
            "frac_filtered": float(n_filt / n_total) if n_total else float("nan"),
            "mean_delta": mean,
            "ci_low": lo, "ci_high": hi,
            "perm_p": p_perm,
            "wilcoxon_p": p_wilc,
        })
        print(f"  {DISPLAY_NAMES[enc]:24s}  "
              f"n={n_filt:5d}/{n_total:5d} ({100*n_filt/n_total:.1f}%)  "
              f"Δ={mean:+.4f}  [{lo:+.4f}, {hi:+.4f}]  "
              f"p_perm={p_perm:.2e}  p_wilc={p_wilc:.2e}")

    out = pd.DataFrame(rows)
    out_path = REPO / "figs" / "results" / "gold_filtered_paired_test_k10.csv"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out.to_csv(out_path, index=False)
    print(f"\nwrote {out_path}")


if __name__ == "__main__":
    main()
