"""Plot the paper's AllSides gold-filtered political retrieval k-sweep.

Writes figs/output/political_ksweep.pdf and .png. The gold-filtered loaders
are also used by plot_political_overview.py for the main political figure.
"""
from __future__ import annotations

import sys
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(REPO / "figs" / "scripts"))

from src.stats import cluster_bootstrap_mean  # noqa: E402
from _style import ENCODER_DISPLAY, ENCODER_ORDER, STANCE_COLOR, apply_rc, save_both  # noqa: E402

OUT = REPO / "figs" / "output"

DENSE_RUN = REPO / "allsides_synth" / "results"
BM25_RUN = DENSE_RUN / "bm25"
DISPLAY_ORDER = list(ENCODER_ORDER) + ["bm25"]
DISPLAY_NAMES = dict(ENCODER_DISPLAY, **{"bm25": "BM25"})

LEFT_COLOR = STANCE_COLOR["left"]      # blue
RIGHT_COLOR = STANCE_COLOR["right"]    # dark red


def _min_story_rank(run_dir: Path) -> pd.DataFrame:
    """Committed gold-filter cache: per (query_id, encoder), the smallest rank
    where any same-story (same AllSides roundup) doc is retrieved. The dense
    cache is regenerated by allsides_synth/scripts/retrieve.py; the bm25/
    cache has no regeneration script."""
    cache = run_dir / "_min_story_rank.parquet"
    if not cache.exists():
        raise FileNotFoundError(
            f"{cache} not found — it is a committed gold-filter cache "
            "(dense run: regenerated by allsides_synth/scripts/retrieve.py; "
            "bm25/: committed only, no regeneration script). "
            "Restore it from git or, for the dense run, re-run retrieval."
        )
    return pd.read_parquet(cache)


def _gold_filtered_bias(run_dir: Path) -> pd.DataFrame:
    """bias_metrics joined with min_story_rank; any_story_retrieved = rank<=k."""
    bm = pd.read_csv(run_dir / "bias_metrics.csv")
    sr = _min_story_rank(run_dir)
    bm = bm.merge(sr, on=["query_id", "encoder"], how="left")
    bm["any_story_retrieved"] = (bm["min_story_rank"] <= bm["k"]).fillna(False)
    return bm


def _per_stance_lean_filtered(bm: pd.DataFrame, k: int) -> pd.DataFrame:
    """Per (encoder, stance) cluster-bootstrap mean lean on PAIRED gold-filtered
    cells: both L and R queries of a cell must have any same-story doc in top-k.
    This matches the paired-Δ formal test (`analyze_political_gold.py`).
    """
    sub_k = bm[bm["k"] == k]
    # Build per-(encoder, article_id, frame) "both passed" mask.
    lr = sub_k[sub_k["stance"].isin(["left", "right"])].copy()
    passes_wide = lr.pivot_table(
        index=["encoder", "article_id", "frame"],
        columns="stance",
        values="any_story_retrieved",
        aggfunc="first",
    )
    passes_wide["both"] = (passes_wide.get("left", False).fillna(False)
                          & passes_wide.get("right", False).fillna(False))
    keep_idx = passes_wide[passes_wide["both"]].index
    lr = lr.set_index(["encoder", "article_id", "frame"])
    lr = lr.loc[lr.index.isin(keep_idx)].reset_index()

    rows = []
    for (enc, stance), g in lr.groupby(["encoder", "stance"]):
        if g.empty:
            continue
        m, lo, hi = cluster_bootstrap_mean(
            g["lean_score"].to_numpy(),
            g["article_id"].to_numpy(),
            n_boot=5000, seed=42,
        )
        rows.append({
            "encoder": enc, "stance": stance, "k": k,
            "n_cells": len(g),
            "mean": m, "ci_low": lo, "ci_high": hi,
        })
    return pd.DataFrame(rows)


def plot_k_sweep() -> None:
    """Per-stance lean for pairs where both queries retrieve a gold article,
    in the 3x2 per-panel-y-axis layout of the paper's k-sweep companions."""
    apply_rc()
    bm_dense = _gold_filtered_bias(DENSE_RUN)
    bm_bm25 = _gold_filtered_bias(BM25_RUN)
    bm = pd.concat([bm_dense, bm_bm25], ignore_index=True)
    K_GRID = [5, 10, 20, 50, 100]
    long = pd.concat([_per_stance_lean_filtered(bm, k) for k in K_GRID],
                     ignore_index=True)

    fig, axes = plt.subplots(3, 2, figsize=(3.4, 4.4), sharey=False, sharex=True)
    axes = axes.flatten()
    for ax, enc in zip(axes, DISPLAY_ORDER):
        sub = long[long["encoder"] == enc]
        y_los, y_his = [], []
        for stance, color in [("left", LEFT_COLOR), ("right", RIGHT_COLOR)]:
            s = sub[sub["stance"] == stance].sort_values("k")
            if s.empty:
                continue
            ax.errorbar(s["k"], s["mean"],
                        yerr=[s["mean"] - s["ci_low"], s["ci_high"] - s["mean"]],
                        fmt="o-", color=color, markersize=3.5,
                        elinewidth=0.7, capsize=1.5, capthick=0.5)
            y_los.extend(s["ci_low"].tolist())
            y_his.extend(s["ci_high"].tolist())
        ax.axhline(0, color="#333", linewidth=0.5, linestyle=":", zorder=0)
        ax.set_xscale("log")
        ax.set_xticks(K_GRID)
        ax.set_xticklabels([str(k) for k in K_GRID], fontsize=6.5)
        ax.set_xlim(4.0, 120)
        ax.set_title(DISPLAY_NAMES[enc], fontsize=7.5, pad=2)
        ax.tick_params(axis="y", labelsize=6.5)
        ax.grid(axis="y", alpha=0.25, lw=0.3)
        if y_los and y_his:
            lo = min(y_los + [0.0])
            hi = max(y_his + [0.0])
            pad = max((hi - lo) * 0.18, 0.005)
            ax.set_ylim(lo - pad, hi + pad)

    fig.text(0.52, 0.005, "top-$k$ cutoff", ha="center", fontsize=8)
    fig.text(0.005, 0.5, r"mean retrieval lean ($\%R-\%L$)",
             va="center", rotation="vertical", fontsize=8)
    fig.tight_layout(rect=[0.035, 0.025, 1.0, 1.0], w_pad=0.8, h_pad=0.6)
    save_both(fig, str(OUT / "political_ksweep"))
    print("wrote political_ksweep")


if __name__ == "__main__":
    plot_k_sweep()
